### ISSUE TITLE
Android 11 repo sync error

### ISSUE THREAD

**Issue by LeoChang88** [technexion-android/cookers#35]
Hello,

I'm trying to build the Android 11 image on Ubuntu 20.04, some errors occurred,
please help to fix them.
[build_log.txt](https://github.com/technexion-android/cookers/files/7471800/build_log.txt)

**Comment by wigcheng** [comment]
Fixed! Thanks for your feedback, please try again, let me know if you still got issues.

**Comment by LeoChang88** [comment]
Some errors still occurred when I building the source code:
[android_log2.txt](https://github.com/technexion-android/cookers/files/7493770/android_log2.txt)

should I create other questions?

**Comment by wigcheng** [comment]
Please refer this post:
https://developer.technexion.com/docs/android-11-arm64-setup-build-and-flashing#starting-compile-the-source-code

It seems download source code has no problems, you just skip one step to execute toolchain download command, thanks.
